/** Declaration file generated by dts-gen */

export = node_odoo;

declare class node_odoo {
    constructor(config: any);

    connect(cb: any): any;

    create(model: any, params: any, callback: any): void;

    delete(model: any, id: any, callback: any): void;

    get(model: any, id: any, callback: any): void;

    search(model: any, params: any, callback: any): void;

    update(model: any, id: any, params: any, callback: any): void;

}

declare namespace node_odoo {
    namespace prototype1 {
        function connect(cb: any): any;

        function create(model: any, params: any, callback: any): void;

        function get(model: any, id: any, callback: any): void;

        function search(model: any, params: any, callback: any): void;

        function update(model: any, id: any, params: any, callback: any): void;

        namespace connect {
            const prototype: {
            };

        }

        namespace create {
            const prototype: {
            };

        }

        namespace get {
            const prototype: {
            };

        }

        namespace search {
            const prototype: {
            };

        }

        namespace update {
            const prototype: {
            };

        }

    }

}

